In [1]:
import os
import random
import h5py
from PIL import Image
import json
# import cv2
import numpy as np

import torch
import sys
sys.path.insert(0, '/home/zhuoyan/vision/meta_dataset')

# from datasets.meta_dataset import dataset_spec as dataset_spec_lib

import datasets

In [2]:
testSet = datasets.datasets['meta-dataset'](split = "test")
trainSet = datasets.datasets['meta-dataset'](split = "train")

In [6]:
trainSet[0]

(tensor([[[[[[-0.8507, -0.8507, -0.8164,  ..., -0.2684, -0.4911, -0.5938],
             [-0.7993, -0.7650, -0.7479,  ..., -0.0801, -0.3027, -0.4568],
             [-0.6794, -0.6794, -0.6452,  ...,  0.0398, -0.0972, -0.2856],
             ...,
             [-1.0562, -1.2445, -1.3815,  ..., -1.0733, -1.3130, -1.1418],
             [-1.0904, -1.2788, -1.3987,  ..., -1.3644, -1.3473, -0.9192],
             [-1.1589, -1.3473, -1.4329,  ..., -1.4329, -1.2103, -0.6281]],
 
            [[ 0.1877,  0.2927,  0.3277,  ...,  0.5378,  0.3452,  0.2577],
             [ 0.2752,  0.3452,  0.3627,  ...,  0.6779,  0.4853,  0.3627],
             [ 0.3978,  0.3978,  0.3452,  ...,  0.8004,  0.6604,  0.4678],
             ...,
             [-0.9328, -1.1253, -1.3004,  ..., -1.0203, -1.2654, -1.1078],
             [-0.9678, -1.1779, -1.3179,  ..., -1.3004, -1.3354, -0.9678],
             [-1.0378, -1.2479, -1.3529,  ..., -1.3529, -1.2129, -0.7402]],
 
            [[-0.4624, -0.3927, -0.2358,  ...,  0.6182,  0

In [3]:
trainSet.datasets

['quickdraw',
 'omniglot',
 'ilsvrc_2012',
 'aircraft',
 'fungi',
 'cu_birds',
 'vgg_flower']

In [4]:
len(trainSet.class_images['fungi'].keys())

994

In [5]:
len(testSet.class_images['fungi'].keys())

200

In [6]:
testSet.class_h5_dict['aircraft']

{85: None,
 86: None,
 87: None,
 88: None,
 89: None,
 90: None,
 91: None,
 92: None,
 93: None,
 94: None,
 95: None,
 96: None,
 97: None,
 98: None,
 99: None}

In [7]:
for key in testSet.class_images['fungi']:
    print(len(testSet.class_images['fungi'][key]))

136
20
84
80
95
9
86
66
45
63
71
173
145
15
49
22
46
24
6
57
100
54
131
18
29
147
23
13
161
63
66
93
217
10
8
7
6
364
219
220
33
26
29
236
8
57
68
29
119
128
143
76
113
14
30
17
31
85
131
106
34
39
33
112
12
12
32
139
11
13
18
20
15
84
129
20
19
68
22
108
36
17
41
54
84
72
123
62
11
148
91
45
22
23
66
40
79
21
7
36
118
76
22
30
9
140
68
129
53
41
8
164
27
49
10
53
198
25
53
12
124
25
19
59
139
122
25
14
154
36
53
10
73
17
22
38
137
50
55
37
29
70
91
28
45
130
15
123
20
49
12
39
169
127
40
73
155
18
92
46
24
12
19
95
54
36
8
80
122
114
161
8
255
21
27
17
22
93
21
13
71
340
101
9
7
65
109
40
37
65
11
27
68
64
38
20
83
55
74
27


In [12]:
trainSet.datasets

['quickdraw',
 'omniglot',
 'ilsvrc_2012',
 'aircraft',
 'fungi',
 'cu_birds',
 'vgg_flower',
 'traffic_sign']

In [6]:
# for domain in testSet.datasets:
#     print(domain)
#     num_imgs = 0
#     print("num classes: ", len(testSet.class_images[domain].keys()))
#     for key, val in testSet.class_images[domain].items():
#         num_imgs += len(val)
#     print("num classes: ", num_imgs)
#     print("======")

for domain in trainSet.datasets:
    print(domain)
    num_imgs = 0
    print("num classes: ", len(trainSet.class_images[domain].keys()))
    for key, val in trainSet.class_images[domain].items():
        num_imgs += len(val)
    print("num classes: ", num_imgs)
    print("======")

quickdraw
num classes:  241
num classes:  34776331
omniglot
num classes:  883
num classes:  17660
ilsvrc_2012
num classes:  712
num classes:  915249
aircraft
num classes:  70
num classes:  7000
fungi
num classes:  994
num classes:  64449
cu_birds
num classes:  140
num classes:  8239
vgg_flower
num classes:  71
num classes:  5655


get item

In [9]:
source = "traffic_sign"

In [10]:
class_ids = list(testSet.class_images[source].keys())
class_ids

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42]

In [7]:
support_images, support_labels, query_images, query_labels = testSet[0]

In [10]:
print(support_images.shape)
print(support_labels)
print(query_images.shape)
print(query_labels)

torch.Size([5, 3, 224, 224])
tensor([92, 94, 86, 96, 90])
torch.Size([75, 3, 224, 224])
tensor([92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 94, 94, 94,
        94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 86, 86, 86, 86, 86, 86,
        86, 86, 86, 86, 86, 86, 86, 86, 86, 96, 96, 96, 96, 96, 96, 96, 96, 96,
        96, 96, 96, 96, 96, 96, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
        90, 90, 90])


In [6]:
for source in testSet.datasets:
    print(source)
    support_images, support_labels, query_images, query_labels = testSet[0]
    print(support_images.shape)
    print(support_labels)
    print(query_images.shape)
    print(query_labels)

quickdraw
torch.Size([5, 3, 224, 224])
tensor([89, 94, 96, 88, 98])
torch.Size([75, 3, 224, 224])
tensor([89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 94, 94, 94,
        94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 96, 96, 96, 96, 96, 96,
        96, 96, 96, 96, 96, 96, 96, 96, 96, 88, 88, 88, 88, 88, 88, 88, 88, 88,
        88, 88, 88, 88, 88, 88, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98,
        98, 98, 98])
omniglot
torch.Size([5, 3, 224, 224])
tensor([85, 90, 98, 86, 88])
torch.Size([75, 3, 224, 224])
tensor([85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 90, 90, 90,
        90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 98, 98, 98, 98, 98, 98,
        98, 98, 98, 98, 98, 98, 98, 98, 98, 86, 86, 86, 86, 86, 86, 86, 86, 86,
        86, 86, 86, 86, 86, 86, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88,
        88, 88, 88])
ilsvrc_2012
torch.Size([5, 3, 224, 224])
tensor([93, 94, 88, 95, 85])
torch.Size([75, 3, 224, 224])
tensor([93, 93, 93, 93,

In [9]:
len(testSet.class_images['aircraft'].keys())

15

### sampled classes as finetuning tasks

In [11]:
trainSet.datasets

['quickdraw',
 'omniglot',
 'ilsvrc_2012',
 'aircraft',
 'fungi',
 'cu_birds',
 'vgg_flower',
 'traffic_sign']

In [7]:
source = 'aircraft'

In [9]:
sampled_classes

array([60, 12, 39,  8, 37, 31, 46, 19, 35,  0, 13, 25, 57,  7, 48])

## method 1

In [30]:
s = 1; q = 9

source = 'aircraft'
deterministic = True
res = []
for idx in range(50):
    d = {}
    if deterministic:
        np.random.seed(idx)
    sampled_classes = np.random.choice(list(trainSet.class_images[source].keys()), 15, replace=False)
    d['source'] = source
    d['task_seed'] = idx
    tmp = {}
    for class_id in sampled_classes:
        # Get all available image indices for the class
        available_indices = trainSet.class_images[source][class_id]

        while len(available_indices) < s + q:  # If not enough images, resample class
            class_id = np.random.choice(list(trainSet.class_images[source].keys()))
            available_indices = trainSet.class_images[source][class_id]

        # Randomly sample images for support and query
        sampled_indices = np.random.choice(available_indices, s + q, replace=False)
        tmp[class_id] = sampled_indices.tolist()
    d['indices'] = tmp
    res.append(d)

In [31]:
d

{'source': 'aircraft',
 'task_seed': 49,
 'indices': {66: ['95', '23', '67', '85', '60', '49', '73', '20', '7', '6'],
  11: ['21', '52', '8', '64', '84', '65', '46', '83', '12', '94'],
  24: ['15', '91', '46', '31', '17', '72', '39', '41', '25', '29'],
  47: ['13', '77', '79', '53', '96', '54', '8', '92', '85', '94'],
  22: ['26', '70', '5', '55', '0', '48', '97', '95', '9', '96'],
  27: ['54', '2', '22', '87', '58', '59', '99', '94', '4', '12'],
  14: ['44', '58', '83', '50', '7', '89', '10', '31', '91', '16'],
  41: ['93', '97', '90', '67', '9', '24', '45', '21', '39', '12'],
  68: ['30', '44', '96', '37', '49', '79', '65', '87', '19', '39'],
  34: ['51', '14', '18', '13', '6', '3', '99', '78', '72', '65'],
  44: ['77', '45', '23', '52', '58', '67', '89', '97', '40', '82'],
  1: ['4', '54', '84', '12', '92', '50', '57', '5', '63', '33'],
  17: ['21', '98', '20', '36', '85', '59', '14', '5', '94', '74'],
  50: ['20', '18', '50', '54', '33', '14', '34', '3', '42', '23'],
  56: ['39', '

In [32]:
res

[{'source': 'aircraft',
  'task_seed': 0,
  'indices': {26: ['7', '40', '95', '45', '31', '5', '59', '55', '33', '83'],
   27: ['17', '34', '6', '15', '55', '36', '88', '82', '57', '89'],
   48: ['6', '62', '98', '88', '92', '59', '1', '34', '89', '65'],
   22: ['15', '91', '28', '93', '89', '14', '32', '67', '43', '21'],
   30: ['54', '39', '58', '3', '28', '99', '80', '78', '37', '19'],
   51: ['51', '58', '13', '74', '67', '23', '15', '38', '40', '87'],
   7: ['17', '63', '98', '7', '96', '14', '31', '99', '43', '16'],
   59: ['89', '74', '2', '58', '42', '39', '98', '18', '70', '60'],
   34: ['89', '44', '31', '46', '32', '91', '28', '95', '82', '12'],
   69: ['85', '40', '48', '20', '38', '32', '99', '94', '46', '54'],
   56: ['48', '12', '62', '1', '86', '24', '14', '5', '43', '52'],
   28: ['62', '5', '85', '92', '93', '45', '43', '20', '25', '11'],
   31: ['85', '11', '33', '90', '14', '86', '45', '0', '93', '6'],
   42: ['59', '96', '26', '79', '23', '47', '39', '31', '53', '4

In [42]:
s = 1; q = 9
deterministic = True
res = []
for source in trainSet.datasets:
    
    for idx in range(50):
        if deterministic:
            np.random.seed(idx)
        sampled_classes = np.random.choice(list(trainSet.class_images[source].keys()), 15, replace=False)
        d = {'source': source}
        d['task_seed'] = idx
        tmp = {}
        for class_id in sampled_classes:
            # Get all available image indices for the class
            available_indices = trainSet.class_images[source][class_id]

            while len(available_indices) < s + q:  # If not enough images, resample class
                class_id = np.random.choice(list(trainSet.class_images[source].keys()))
                available_indices = trainSet.class_images[source][class_id]

            # Randomly sample images for support and query
            sampled_indices = np.random.choice(available_indices, s + q, replace=False)
            tmp[class_id] = sampled_indices.tolist()
        d['indices'] = tmp
        res.append(d)

In [43]:
res[-3:]

[{'source': 'vgg_flower',
  'task_seed': 47,
  'indices': {42: ['33', '16', '5', '2', '10', '3', '11', '42', '44', '29'],
   36: ['59', '1', '56', '36', '25', '37', '4', '13', '2', '69'],
   5: ['10', '5', '72', '16', '43', '32', '2', '30', '65', '76'],
   53: ['8', '34', '5', '41', '15', '48', '4', '20', '59', '27'],
   39: ['5', '6', '58', '22', '34', '59', '49', '57', '48', '37'],
   16: ['85', '122', '36', '29', '18', '99', '21', '97', '82', '60'],
   63: ['29', '11', '52', '26', '57', '28', '27', '46', '31', '3'],
   30: ['3', '71', '39', '19', '46', '40', '29', '74', '37', '52'],
   44: ['13', '58', '35', '85', '66', '40', '67', '51', '33', '1'],
   62: ['11', '54', '60', '39', '62', '32', '38', '2', '59', '37'],
   56: ['49', '65', '21', '55', '7', '17', '56', '10', '41', '3'],
   54: ['65', '31', '28', '45', '9', '63', '44', '17', '34', '41'],
   61: ['15', '43', '27', '19', '47', '0', '9', '53', '38', '25'],
   14: ['40', '62', '92', '34', '104', '15', '26', '32', '39', '125']

## method 2

In [46]:
s = 1; q = 9

source = 'aircraft'
deterministic = True
res = []
for idx in range(50):
    d = {}
    if deterministic:
        np.random.seed(idx)
    sampled_classes = np.random.choice(list(trainSet.class_images[source].keys()), 15, replace=False)
    d['source'] = source
    d['task_seed'] = idx
    flat_classes_images = []
    for class_id in sampled_classes:
        # Get all available image indices for the class
        available_indices = trainSet.class_images[source][class_id]

        while len(available_indices) < s + q:  # If not enough images, resample class
            class_id = np.random.choice(list(trainSet.class_images[source].keys()))
            available_indices = trainSet.class_images[source][class_id]

        # Randomly sample images for support and query
        sampled_indices = np.random.choice(available_indices, s + q, replace=False)
        flat_class_images = [(class_id, idx) for idx in sampled_indices]

        flat_classes_images += flat_class_images
    d['indices'] = flat_classes_images
    res.append(d)

In [54]:
np.array([cls_id for cls_id, sample_id in res[0]['indices']])

array([26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 56, 56,
       56, 56, 56, 56, 56, 56, 56, 56, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 42, 42, 42, 42, 42, 42,
       42, 42, 42, 42, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33])

In [58]:
(np.bincount(np.array([cls_id for cls_id, sample_id in res[0]['indices']])) == 10).sum()

15

In [3]:
s = 1; q = 9
deterministic = True
res = []
for source in trainSet.datasets:
    
    for idx in range(100):
        if deterministic:
            np.random.seed(idx)
        sampled_classes = np.random.choice(list(trainSet.class_images[source].keys()), 15, replace=False)
        d = {'source': source}
        d['task_seed'] = idx
        flat_classes_images = []
        for class_id in sampled_classes:
            # Get all available image indices for the class
            available_indices = trainSet.class_images[source][class_id]

            while len(available_indices) < s + q:  # If not enough images, resample class
                class_id = np.random.choice(list(trainSet.class_images[source].keys()))
                available_indices = trainSet.class_images[source][class_id]

            # Randomly sample images for support and query
            sampled_indices = np.random.choice(available_indices, s + q, replace=False)
            flat_class_images = [(class_id, idx) for idx in sampled_indices]

            flat_classes_images += flat_class_images
        d['indices'] = flat_classes_images
        res.append(d)

In [4]:
res[-3:]

[{'source': 'vgg_flower',
  'task_seed': 97,
  'indices': [(33, '68'),
   (33, '69'),
   (33, '57'),
   (33, '94'),
   (33, '67'),
   (33, '44'),
   (33, '56'),
   (33, '65'),
   (33, '83'),
   (33, '22'),
   (18, '121'),
   (18, '153'),
   (18, '65'),
   (18, '104'),
   (18, '59'),
   (18, '72'),
   (18, '122'),
   (18, '101'),
   (18, '26'),
   (18, '76'),
   (21, '23'),
   (21, '16'),
   (21, '36'),
   (21, '42'),
   (21, '33'),
   (21, '27'),
   (21, '41'),
   (21, '20'),
   (21, '9'),
   (21, '32'),
   (39, '18'),
   (39, '13'),
   (39, '37'),
   (39, '6'),
   (39, '36'),
   (39, '45'),
   (39, '42'),
   (39, '28'),
   (39, '25'),
   (39, '31'),
   (2, '74'),
   (2, '14'),
   (2, '83'),
   (2, '85'),
   (2, '11'),
   (2, '53'),
   (2, '84'),
   (2, '37'),
   (2, '77'),
   (2, '33'),
   (27, '9'),
   (27, '26'),
   (27, '37'),
   (27, '16'),
   (27, '31'),
   (27, '25'),
   (27, '43'),
   (27, '36'),
   (27, '8'),
   (27, '52'),
   (46, '11'),
   (46, '49'),
   (46, '29'),
   (46, 

In [5]:
for item in res:
    item['indices'] = [(int(index), label) for index, label in item['indices']]

In [6]:
import json

# Assuming your list of dictionaries is named 'res'
with open('/datadrive2/datasets/meta_dataset_taskEmb/100_per_domain/finetuning_tasks_indices.json', 'w') as json_file:
    json.dump(res, json_file, indent = 4)


In [7]:
import json

# Assuming your list of dictionaries is named 'res'
with open('/datadrive2/datasets/meta_dataset_taskEmb/100_per_domain/finetuning_tasks_indices2.json', 'w') as json_file:
    json.dump(res, json_file)


'/home/zhuoyan/vision/meta_dataset/notebook'

In [1]:
import json

with open('finetuning_tasks_indices2.json', 'r') as json_file:
    loaded_data = json.load(json_file)

print(loaded_data)


[{'source': 'quickdraw', 'task_seed': 0, 'indices': [[109, '112791'], [109, '89573'], [109, '134642'], [109, '8586'], [109, '36001'], [109, '27732'], [109, '31876'], [109, '33289'], [109, '123119'], [109, '99612'], [71, '96168'], [71, '99894'], [71, '35070'], [71, '19463'], [71, '81576'], [71, '36476'], [71, '59926'], [71, '27211'], [71, '26105'], [71, '105942'], [37, '106563'], [37, '100443'], [37, '35526'], [37, '31914'], [37, '51487'], [37, '54601'], [37, '108665'], [37, '112252'], [37, '42074'], [37, '115257'], [74, '116316'], [74, '33159'], [74, '94675'], [74, '11793'], [74, '2329'], [74, '45039'], [74, '21548'], [74, '28394'], [74, '18241'], [74, '79939'], [108, '45630'], [108, '78559'], [108, '20922'], [108, '41744'], [108, '100921'], [108, '105031'], [108, '28785'], [108, '69726'], [108, '98107'], [108, '9458'], [228, '39807'], [228, '45979'], [228, '161478'], [228, '98145'], [228, '40654'], [228, '90771'], [228, '107783'], [228, '112787'], [228, '57853'], [228, '146466'], [156

In [2]:
loaded_data

[{'source': 'quickdraw',
  'task_seed': 0,
  'indices': [[109, '112791'],
   [109, '89573'],
   [109, '134642'],
   [109, '8586'],
   [109, '36001'],
   [109, '27732'],
   [109, '31876'],
   [109, '33289'],
   [109, '123119'],
   [109, '99612'],
   [71, '96168'],
   [71, '99894'],
   [71, '35070'],
   [71, '19463'],
   [71, '81576'],
   [71, '36476'],
   [71, '59926'],
   [71, '27211'],
   [71, '26105'],
   [71, '105942'],
   [37, '106563'],
   [37, '100443'],
   [37, '35526'],
   [37, '31914'],
   [37, '51487'],
   [37, '54601'],
   [37, '108665'],
   [37, '112252'],
   [37, '42074'],
   [37, '115257'],
   [74, '116316'],
   [74, '33159'],
   [74, '94675'],
   [74, '11793'],
   [74, '2329'],
   [74, '45039'],
   [74, '21548'],
   [74, '28394'],
   [74, '18241'],
   [74, '79939'],
   [108, '45630'],
   [108, '78559'],
   [108, '20922'],
   [108, '41744'],
   [108, '100921'],
   [108, '105031'],
   [108, '28785'],
   [108, '69726'],
   [108, '98107'],
   [108, '9458'],
   [228, '39807']

In [3]:
len(loaded_data)

350